frase = str(input('Digite uma frase: ')).upper().strip()
print('A letra A aparece {} vezes na frase'.format(frase.count('A')))
print('Ela aparece na {} posição na primeira vez'.format(frase.find('A')+1))
print('A ultima ocorrencia é na posição {}'.format(frase.rfind('A')+1))
#print(frase.count('a', 0, 4))