n = str(input('Qual o seu nome completo: ')).strip() 
#print(n.upper() == 'Silva')n.find('Silva')
#print('Silva' in n) 
#print(n.upper().find('Silva'))
#print(n[:100].upper() == 'Silva') 
print('Seu nome tem Silva {}'.format('silva' in n.lower()))
